export const individualKarts = [
    {
        id: 1,
        characterName: 'Mario',
        kart: 'Standard Kart',
        img: 'assets/MarioStandardKart.png',
        isInCollection: false,
    },
    {
        id: 2,
        characterName: 'Mario',
        kart: 'Circuit Special',
        img: 'assets/MarioCircuitSpecial.png',
        isInCollection: false,
    },
    {
        id: 3,
        characterName: 'Mario',
        kart: 'P-Wing',
        img: 'assets/MarioP-Wing.png',
        isInCollection: false,
    },
    {
        id: 4,
        characterName: 'Mario',
        kart: 'Wild Wing',
        img: 'assets/MarioWildWing.png',
        isInCollection: false,
    },
    {
        id: 101,
        characterName: 'Mario Tanooki',
        kart: 'Standard Kart',
        img: 'assets/MarioTanookiStandardKart.png',
        isInCollection: false,
    },
    {
        id: 102,
        characterName: 'Mario Tanooki',
        kart: 'Bumble V',
        img: 'assets/MarioTanookiBumbleV.png',
        isInCollection: false,
    },
    /*
    {
        id: 3901,
        characterName: 'Cat Mario',
        kart: '',
        isInCollection: false,
    },
    */
    {
        id: 201,
        characterName: 'Baby Mario',
        kart: 'B-Dasher',
        img: 'assets/BabyMarioB-Dasher.png',
        isInCollection: false,
    },
    /*
    {
        id: 202,
        characterName: 'Baby Mario',
        kart: 'Pipe Frame',
        isInCollection: false,
    },
    */
    {
        id: 301,
        characterName: 'Luigi',
        kart: 'Standard Kart',
        img: 'assets/LuigiStandardKart.png',
        isInCollection: false,
    },
    {
        id: 302,
        characterName: 'Luigi',
        kart: 'Mach 8',
        img: 'assets/LuigiMach8.png',
        isInCollection: false,
    },
    {
        id: 303,
        characterName: 'Luigi',
        kart: 'Circuit Special',
        img: 'assets/LuigiCircuitSpecial.png',
        isInCollection: false,
    },
    {
        id: 401,
        characterName: 'Baby Luigi',
        kart: 'Sneeker',
        img: 'assets/BabyLuigiSneeker.png',
        isInCollection: false,
    },
    {
        id: 501,
        characterName: 'Peach',
        kart: 'Standard Kart',
        img: 'assets/PeachStandardKart.png',
        isInCollection: false,
    },
    {
        id: 502,
        characterName: 'Peach',
        kart: 'P-Wing',
        img: 'assets/PeachP-Wing.png',
        isInCollection: false,
    },
    {
        id: 601,
        characterName: 'Cat Peach',
        kart: 'Standard Kart',
        img: 'assets/CatPeachStandardKart.png',
        isInCollection: false,
    },
    /*
    {
        id: 4001,
        characterName: 'Baby Peach',
        kart: 'Pipe Frame',
        isInCollection: false,
    },
    */
    {
        id: 701,
        characterName: 'Princess Daisy',
        kart: 'Wild Wing',
        img: 'assets/PrincessDaisyWildWing.png',
        isInCollection: false,
    },
    /*
    {
        id: 4101,
        characterName: 'Baby Daisy',
        kart: '',
        isInCollection: false,
    },
    */
    {
        id: 801,
        characterName: 'Rosalina',
        kart: 'Standard Kart',
        img: 'assets/RosalinaStandardKart.png',
        isInCollection: false,
    },
    {
        id: 802,
        characterName: 'Rosalina',
        kart: 'Birthday Girl',
        img: 'assets/RosalinaBirthdayGirl.png',
        isInCollection: false,
    },
    /*
    {
        id: 4201,
        characterName: 'Baby Rosalina',
        kart: '',
        isInCollection: false,
    },
    */
    {
        id: 901,
        characterName: 'Yoshi',
        kart: 'Standard Kart',
        img: 'assets/YoshiStandardKart.png',
        isInCollection: false,
    },
    {
        id: 902,
        characterName: 'Yoshi',
        kart: 'Pipe Frame',
        img: 'assets/YoshiPipeFrame.png',
        isInCollection: false,
    },
    {
        id: 903,
        characterName: 'Yoshi',
        kart: 'B-Dasher',
        img: 'assets/YoshiB-Dasher.png',
        isInCollection: false,
    },
    {
        id: 904,
        characterName: 'Yoshi',
        kart: 'Mach 8',
        img: 'assets/YoshiMach8.png',
        isInCollection: false,
    },
    {
        id: 1001,
        characterName: 'Red Yoshi',
        kart: 'Standard Kart',
        img: 'assets/RedYoshiStandardKart.png',
        isInCollection: false,
    },
    {
        id: 1101,
        characterName: 'Blue Yoshi',
        kart: 'Standard Kart',
        img: 'assets/BlueYoshiStandardKart.png',
        isInCollection: false,
    },
    {
        id: 1201,
        characterName: 'Light-Blue Yoshi',
        kart: 'Standard Kart',
        img: 'assets/Light-BlueYoshiStandardKart.png',
        isInCollection: false,
    },
    /*
    {
        id: 1301,
        characterName: 'Orange Yoshi',
        kart: 'Standard Kart',
        isInCollection: false,
    },
    {
        id: 1401,
        characterName: 'Yellow Yoshi',
        kart: 'Standard Kart',
        isInCollection: false,
    },
    {
        id: 1501,
        characterName: 'Pink Yoshi',
        kart: 'Standard Kart',
        isInCollection: false,
    },
    {
        id: 1601,
        characterName: 'Black Yoshi',
        kart: 'Standard Kart',
        isInCollection: false,
    },
    {
        id: 1701,
        characterName: 'White Yoshi',
        kart: 'Standard Kart',
        isInCollection: false,
    }, 
    */
    {
        id: 1801,
        characterName: 'Toad',
        kart: 'Standard Kart',
        img: 'assets/ToadStandardKart.png',
        isInCollection: false,
    },
    {
        id: 1802,
        characterName: 'Toad',
        kart: 'Sneeker',
        img: 'assets/ToadSneeker.png',
        isInCollection: false,
    },
    {
        id: 1803,
        characterName: 'Toad',
        kart: 'Mach 8',
        img: 'assets/ToadMach8.png',
        isInCollection: false,
    },
    {
        id: 1901,
        characterName: 'Toadette',
        kart: 'Birthday Girl',
        img: 'assets/ToadetteBirthdayGirl.png',
        isInCollection: false,
    },
    {
        id: 2001,
        characterName: 'Donkey Kong',
        kart: 'Standard Kart',
        img: 'assets/DonkeyKongStandardKart.png',
        isInCollection: false,
    },
    {
        id: 2002,
        characterName: 'Donkey Kong',
        kart: 'Sports Coupe',
        img: 'assets/DonkeyKongSportsCoupe.png',
        isInCollection: false,
    },
    {
        id: 2101,
        characterName: 'Diddy Kong',
        kart: 'Pipe Frame',
        img: 'assets/DiddyKongPipeFrame.png',
        isInCollection: false,
    },
    {
        id: 2201,
        characterName: 'Bowser',
        kart: 'Standard Kart',
        img: 'assets/BowserStandardKart.png',
        isInCollection: false,
    },
    {
        id: 2202,
        characterName: 'Bowser',
        kart: 'Badwagon',
        img: 'assets/BowserBadwagon.png',
        isInCollection: false,
    },
    {
        id: 2301,
        characterName: 'Dry Bowser',
        kart: 'Standard Kart',
        img: 'assets/DryBowserStandardKart.png',
        isInCollection: false,
    },
    {
        id: 2401,
        characterName: 'Bowser Jr',
        kart: 'Flame Flyer',
        img: 'assets/BowserJrFlameFlyer.png',
        isInCollection: false,
    },
    {
        id: 2501,
        characterName: 'Shy Guy',
        kart: 'Standard Kart',
        img: 'assets/ShyGuyStandardKart.png',
        isInCollection: false,
    },
    {
        id: 2502,
        characterName: 'Shy Guy',
        kart: 'B-Dasher',
        img: 'assets/ShyGuyB-Dasher.png',
        isInCollection: false,
    },
    {
        id: 2601,
        characterName: 'Light-Blue Shy Guy',
        kart: 'Standard Kart',
        img: 'assets/Light-BlueShyGuyStandardKart.png',
        isInCollection: false,
    },
    /*
    {
        id: 2701,
        characterName: 'Black Shy Guy',
        kart: 'Standard Kart',
        isInCollection: false,
    },
    {
        id: 2801,
        characterName: 'Green Shy Guy',
        kart: 'Standard Kart',
        isInCollection: false,
    },
    {
        id: 2901,
        characterName: 'Yellow Shy Guy',
        kart: 'Standard Kart',
        isInCollection: false,
    },
    {
        id: 3001,
        characterName: 'White Shy Guy',
        kart: 'Standard Kart',
        isInCollection: false,
    },
    {
        id: 3101,
        characterName: 'Blue Shy Guy',
        kart: 'Standard Kart',
        isInCollection: false,
    },
    {
        id: 3201,
        characterName: 'Pink Shy Guy',
        kart: 'Standard Kart',
        isInCollection: false,
    },
    {
        id: 3301,
        characterName: 'Orange Shy Guy',
        kart: 'Standard Kart',
        isInCollection: false,
    },
    */
    {
        id: 3401,
        characterName: 'Wario',
        kart: 'Standard Kart',
        img: 'assets/WarioStandardKart.png',
        isInCollection: false,
    },
    {
        id: 3402,
        characterName: 'Wario',
        kart: 'Badwagon',
        img: 'assets/WarioBadwagon.png',
        isInCollection: false,
    },
    {
        id: 3501,
        characterName: 'Waluigi',
        kart: 'Badwagon',
        img: 'assets/WaluigiBadwagon.png',
        isInCollection: false,
    },
    {
        id: 3601,
        characterName: 'Koopa Troopa',
        kart: 'Circuit Special',
        img: 'assets/KoopaTroopaCircuitSpecial.png',
        isInCollection: false,
    },
    {
        id: 3701,
        characterName: 'Dry Bones',
        kart: 'Standard Kart',
        img: 'assets/DryBonesStandardKart.png',
        isInCollection: false,
    },
    {
        id: 3801,
        characterName: 'Lakitu',
        kart: 'Sports Coupe',
        img: 'assets/LakituSportsCoupe.png',
        isInCollection: false,
    }
]